name: anidopt
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.5+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # Networking
  json_annotation: ^4.8.1



  # ui
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  flutter_native_splash: ^2.3.6
  carousel_slider: ^4.2.1
  flutter_lazy_indexed_stack: ^0.0.6
  material_design_icons_flutter: ^7.0.7296
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.9
  country_code_picker: ^3.0.0
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.0
  modal_bottom_sheet: ^3.0.0-pre
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  flutter_html: ^3.0.0-beta.2
  flutter_hooks: ^0.20.3
  share_plus: ^7.2.1
  webview_flutter: ^4.4.2
  pin_code_fields: ^8.0.1
  lottie: ^2.7.0
  google_maps_flutter: ^2.5.2
  flutter_map_location_picker: ^0.0.4
  flutter_onboarding_slider: ^1.0.11




  # dependency
  get_it: ^7.6.4

  # state management
  flutter_bloc: ^8.1.3

  # storage
  get_storage: ^2.1.1

  # data
  equatable: ^2.0.5
  envied: ^0.5.2


  # database
  floor: ^1.4.2

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.9.0
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.7.7
  firebase_crashlytics: ^3.0.11
  firebase_database: ^10.0.9
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  # utilities
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  encrypt: ^5.0.3
  collection: ^1.18.0
  flutter_local_notifications: ^16.2.0
  url_launcher: ^6.2.2
  uni_links: ^0.5.1
  device_preview: ^1.1.0
  package_info_plus: ^5.0.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  geocode: ^1.0.3
  latlong2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # build runner
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

  # networking
  retrofit_generator: '>=5.0.0 <6.0.0'
  json_serializable: ^6.7.1

  # auto route
  auto_route_generator: ^7.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/


  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700